### ISSUE TITLE
Identify Fields produces no output

### ISSUE THREAD

**Issue by psychofarm** [RobHolme/vscode-hl7tools#7]
Steps to produce:  

- Open some_file.hl7  
- Inspect file using HL7 Tools 1.8.0 and use features like Highlight Field.  
- Highlighting works.  
- Select the segment in the message using the cursor.
- Press F1 --> HL7 Tools: Display Segment Fields.  
- The selected segment's fields should be displayed in the output window but the output is empty.  

Screen shot of my Output in VS Code:  

![image](https://user-images.githubusercontent.com/23420335/38840528-27b0e9be-41ae-11e8-87f1-dafc6d704828.png)

**Comment by RobHolme** [comment]
Hi Frank,

I'm having trouble reproducing the issue at my end. Are you able to share the file you are testing with so I can see if there is something specific to the HL7 file I'm not handling correctly? If the file can't de-identified (or is not appropriate to share) could you try reproducing the issue with the test file I have attached. If the test file works, it may point back to something specific to your files that the extension isn't handling.

I noticed the title of the issue referenced the 'Identify Fields' function. This function doesn't produce any output other than adding the pop-up descriptions. The issue description mentions the issue is with the  'Display Segment Fields' function - just confirming the issue is with 'Display Segment Fields' not 'Identify Fields'?

[test.zip](https://github.com/RobHolme/vscode-hl7tools/files/1919556/test.zip)

Rob.

**Comment by RobHolme** [comment]
Hi,

Were you able to reproduce the issue with the test hl7 file? 

Rob.

**Comment by RobHolme** [comment]
I'm still unable to reproduce the issue. Feel free to reopen if you are able to supply a HL7 file that triggers the issue that I can test with, or have time to test using the file I attached.
