### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by edimaster** [RobHolme/vscode-hl7tools#9]
Hi Rob,

Is there a config file somewhere which i can configure to stop displaying the fields as "undefined"

![image](https://user-images.githubusercontent.com/43253476/45661059-776eba80-bac1-11e8-8fc1-c16804a2f7bb.png)

**Comment by RobHolme** [comment]
Hi Nicholas,

The segment and field descriptions should be included, you should only see the 'undefined' description for custom 'Z' segments.

Here is an example of what you should see for a segment defined in the schema such as the PID segment:
![image](https://user-images.githubusercontent.com/23287323/45684372-a85df680-bb78-11e8-94da-81bb9fe17efb.png)

For some reason your PID segment is being treated as a custom segment - this should only occur if the segment is not included in the schema . e.g:
![image](https://user-images.githubusercontent.com/23287323/45684854-27076380-bb7a-11e8-90ac-170f0ede6f44.png)

I have no idea why this is happening - the files defining the field and segment descriptions are included with the extension. Maybe try uninstalling, then re-installing the extension? Otherwise try the debugging steps I suggested in the previous issue to see if it provides any further details.

regards,
Rob.

**Comment by edimaster** [comment]
Rob,

I identified the issue. When I copied the message out of the EMR and pasted it into VSC, it prefixed each line with a numeric identifier 1, 2, 3, etc. Once I removed those leading characters the segment was recognized as a non-custom segment. Thank you!

**Comment by RobHolme** [comment]
I've released an updated version of the extension that should now ignore any text that is prefixed to the segment when running the 'Display Segment Fields' command.

Note: Other functionality will still be impacted if the file contains text prefixed to the segments. e.g. the field descriptions won't be displayed when you hover the mouse over a field. When I get time I'll look updating all functions to tolerate text prefixed to segments.
